// Generated by CoffeeScript 1.12.2
(function() {
  var CONFIG, americano;

  CONFIG = require('config');

  americano = require('americano');

  americano.start({
    name: 'wikidata-agent',
    host: CONFIG.host,
    port: CONFIG.port
  });

}).call(this);

//# sourceMappingURL=wikidata-agent.js.map
