// Generated by CoffeeScript 1.12.2
(function() {
  module.exports = {
    host: '0.0.0.0',
    port: 4115,
    wikidata: {
      base: "http://w.b-ol.de/w/api.php",
      username: 'customize',
      password: 'customize'
    },
    whitelistedProperties: {
      P4: 'string',
      P50: 'claim',
      P101: 'claim',
      P103: 'claim',
      P123: 'claim',
      P135: 'claim',
      P136: 'claim',
      P137: 'claim',
      P138: 'claim',
      P179: 'claim',
      P155: 'claim',
      P156: 'claim',
      P212: 'string',
      P291: 'claim',
      P361: 'claim',
      P364: 'claim',
      P577: 'time',
      P648: 'string',
      P674: 'claim',
      P737: 'claim',
      P856: 'string',
      P921: 'claim',
      P953: 'string',
      P957: 'string',
      P1104: 'quantity',
      P1476: 'monolingualtext',
      P1680: 'monolingualtext',
      P2002: 'string',
      P2034: 'string',
      P2093: 'string',
      P2770: 'claim',
      P2848: 'claim',
      P3035: 'string'
    }
  };

}).call(this);

//# sourceMappingURL=default.js.map
