// Generated by CoffeeScript 1.12.2
(function() {
  module.exports = {
    wikidata: {
      username: "Christopher",
      password: "khatru71"
    }
  };

}).call(this);

//# sourceMappingURL=local.js.map
