// Generated by CoffeeScript 1.12.2
(function() {
  var fs, localConfigPath, passwordKey, prompt, saveLocalConfig, usernameKey;

  prompt = require('prompt');

  require('colors');

  fs = require('fs');

  localConfigPath = './config/local.coffee';

  saveLocalConfig = function(username, password) {
    var file;
    file = "module.exports =\n  wikidata:\n    username: \"" + username + "\"\n    password: \"" + password + "\"\n";
    return fs.writeFileSync(localConfigPath, file);
  };

  usernameKey = 'Wikidata username';

  passwordKey = 'Wikidata password';

  console.log("Building local config file".green);

  prompt.start();

  prompt.get([usernameKey, passwordKey], function(err, res) {
    if (err != null) {
      return console.error('prompt error'.red, err);
    } else {
      saveLocalConfig(res[usernameKey], res[passwordKey]);
      console.log("Local config created".green);
      console.log("You still have the possibility to edit it manually at".grey, localConfigPath);
      return console.log('Next step, start the server:'.grey, 'npm start');
    }
  });

}).call(this);

//# sourceMappingURL=init_local_config.js.map
