// Generated by CoffeeScript 1.12.2
(function() {
  var _, createEntity, errors_, ref, simpleArchive, simpleRepeatingHistory;

  _ = require('../lib/utils');

  errors_ = require('../lib/errors');

  ref = require('../lib/archives'), simpleRepeatingHistory = ref.simpleRepeatingHistory, simpleArchive = ref.simpleArchive;

  createEntity = require('../lib/create_entity');

  module.exports = {
    post: function(req, res, next) {
      var body, key;
      body = req.body;
      if (body == null) {
        return errors_.e400(res, 'empty body');
      }
      _.log(body, 'body');
      key = body.key;
      if (key == null) {
        return errors_.e400(res, 'missing key');
      }
      if (simpleRepeatingHistory(key)) {
        return errors_.e400(res, 'entity already added');
      }
      return createEntity(body).then(simpleArchive.bind(null, key)).then(res.json.bind(res))["catch"](errors_.e500.bind(null, res));
    }
  };

}).call(this);

//# sourceMappingURL=entity.js.map
