// Generated by CoffeeScript 1.12.2
(function() {
  module.exports = {
    get: function(req, res, next) {
      return res.json({
        ok: true,
        claim: {
          endpoint: '/claim',
          queries: {
            p: '/^P[0-9]+$/',
            q: '/^Q[0-9]+$/'
          },
          example: '/claim?p=P50&q=Q535'
        }
      });
    }
  };

}).call(this);

//# sourceMappingURL=index.js.map
