// Generated by CoffeeScript 1.12.2
(function() {
  var claim, entity, index, label;

  index = require('./index');

  entity = require('./entity');

  claim = require('./claim');

  label = require('./label');

  module.exports = {
    '': {
      get: index.get
    },
    'entity': {
      post: entity.post
    },
    'claim': {
      post: claim.post
    },
    'label': {
      post: label.post
    },
    'ping': {
      get: function(req, res, next) {
        return res.json({
          ok: true,
          message: 'hello! how do you do?'
        });
      }
    }
  };

}).call(this);

//# sourceMappingURL=routes.js.map
