// Generated by CoffeeScript 1.12.2
(function() {
  var archives, archivesPath, fs, updateFile;

  archivesPath = 'data/archives.json';

  archives = require("../../" + archivesPath);

  fs = require('fs');

  module.exports = {
    updateArchives: function(entity, property, value) {
      var base;
      archives[entity] || (archives[entity] = {});
      (base = archives[entity])[property] || (base[property] = {});
      archives[entity][property][value] = true;
      updateFile();
    },
    repeatingHistory: function(entity, property, value) {
      var ref, ref1;
      return ((ref = archives[entity]) != null ? (ref1 = ref[property]) != null ? ref1[value] : void 0 : void 0) != null;
    },
    simpleArchive: function(key, data) {
      archives[key] = true;
      updateFile();
      return data;
    },
    simpleRepeatingHistory: function(key) {
      return archives[key] != null;
    }
  };

  updateFile = function() {
    return fs.writeFileSync("./" + archivesPath, JSON.stringify(archives, null, 2));
  };

}).call(this);

//# sourceMappingURL=archives.js.map
