// Generated by CoffeeScript 1.12.2
(function() {
  var _, util;

  _ = require('../lib/utils');

  util = require('util');

  module.exports = {
    e400: function(res, message, ctx) {
      _.warn([message, ctx], 'e400');
      res.status(400);
      return res.json({
        status_verbose: message != null ? message.slice(0, 501) : void 0
      });
    },
    e500: function(res, err) {
      var context, message, stack;
      context = err.context, message = err.message, stack = err.stack;
      _.inspect(err, 'err messages');
      _.error(err, 'e500');
      res.status(500);
      return res.json({
        context: context,
        status_verbose: message != null ? message.slice(0, 501) : void 0
      });
    }
  };

}).call(this);

//# sourceMappingURL=errors.js.map
