// Generated by CoffeeScript 1.12.2
(function() {
  var fs, packageData, userAgent, version;

  fs = require('fs');

  packageData = fs.readFileSync('./package.json', 'utf-8');

  version = JSON.parse(packageData).version;

  userAgent = "Wikidata-agent/" + version + " (https://github.com/maxlath/wikidata-agent)";

  console.log('User-Agent:', userAgent.green);

  module.exports = userAgent;

}).call(this);

//# sourceMappingURL=user_agent.js.map
