// Generated by CoffeeScript 1.12.2
(function() {
  var Promise, _, log_, qs, util, utils_;

  _ = require('lodash');

  utils_ = require('inv-utils')(_);

  log_ = require('inv-loggers');

  qs = require('querystring');

  util = require('util');

  Promise = require('bluebird');

  Promise.config({
    warnings: true,
    longStackTraces: true
  });

  module.exports = _.extend(_, utils_, log_, {
    buildUrl: function(base, query) {
      query = qs.stringify(query);
      return base + "?" + query;
    },
    start: function() {
      return Promise.resolve();
    },
    ErrorRethrow: function(label) {
      var errHandler;
      return errHandler = function(err) {
        log_.error(err, label);
        throw err;
      };
    },
    inspect: function(obj) {
      return console.log('inspect'.green, util.inspect(obj, false, null));
    }
  });

}).call(this);

//# sourceMappingURL=utils.js.map
